### ISSUE TITLE
Pass readout config entries to CcdReadout class

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/imSim#346]
These entries in the `output` section of the config
```
    readout:
        # Convert from e-image to realized amp images
        readout_time: 3.
        dark_current: 0.02
        bias_level: 1000.
        pcti: 1.e-6
        scti: 1.e-6
```
should be passed to the `CcdReadout` class.
